### ISSUE TITLE
S1 - L19 Controlled Component

### ISSUE THREAD

**Issue by ghun131** [freeCodeCamp-Hanoi/learn-react-udemy#4]
```javascript
class SearchBar extends Component {
    constructor(props) {
        super(props);

        this.state = { term: '' };
    }

    render() {
        return ( 
            <div>
                <input onChange={(event) => this.setState({ term: event.target.value })} />
            </div>
        );
    }

}
```

Cái này là khi input thay đổi thì state thay đổi. Nghĩa là input bắt state thay đổi theo input. Nhưng tốt hơn sẽ phải là ngược lại, nghĩa là state sẽ phải bắt input thay đổi theo giá trị của state. Vì thế nên code được thay đổi thêm một dòng `value={this.state.term}`
Và nó sẽ là 

```javascript
class SearchBar extends Component {
    constructor(props) {
        super(props);

        this.state = { term: 'Starting Value' };
    }

    render() {
        return ( 
            <div>
                <input 
                value={this.state.term}
                onChange={(event) => this.setState({ term: event.target.value })} />
            </div>
        );
    }

}
```

Trong trường hợp này, input được gán giá trị bằng `{this.state.term}` nên nó biến thành controlled component (controlled form element). Ban đầu thì input vẫn sẽ báo với state giá trị mới của nó, nhưng sau đó SetState sẽ khiến cho component render lại một lần nữa và lần này thì giá trị của input sẽ thay đổi (term mới).
Điều quan trọng là khi người sử dụng (user) gõ một từ nào đó vào input thì input không thực sự thay đổi mà họ tạo ra một event và vì SetState cập nhật giá trị mới nên input mới thay đổi (hết sức vòng vèo)

**Comment by ngminhtrung** [comment]
@hungHoangDang : hơ hơ anh thấy nó dễ hiểu mà =)). Nghe em giải thích xong thấy vòng vèo vãi :P.

Chu trình của nó là: **input** -> **event handler** -> **setState** -> **state** -> **render input**

Mục đích của nó là để mọi thứ phải qua state. Và React nó như thằng giám sát sau lưng, hễ thấy state của component nào thay đổi, là sẽ tự động re-render lại component đấy, ko cần người dùng đụng tay vô.

**Comment by ghun131** [comment]
Đoạn này e nghĩ là Stephen thay đổi dòng dữ liệu nhưng lần đầu tiên e thấy nó nên còn hơi thắc mắc.
